In [273]:
import numpy as np
import pandas as pd

In [274]:
data = np.load("clean_train.npy")
data_test = np.load("clean_test.npy")

In [275]:
data[-1]

{'A': 770.0,
 'S': 409.0,
 'SS': 21.0,
 'age': None,
 'country': 'Germany',
 'country_rank': 622,
 'favourite_beatmapset_count': 57,
 'follower_count': 213,
 'hit_accuracy': 98.2608,
 'is_active': True,
 'is_supporter': False,
 'join_date': '2013-09-18',
 'level': 100,
 'maximum_combo': 2232,
 'monthly_playcounts': [{'count': 2, 'start_date': '2013-09-01'},
  {'count': 1050, 'start_date': '2013-12-01'},
  {'count': 2557, 'start_date': '2014-01-01'},
  {'count': 2751, 'start_date': '2014-02-01'},
  {'count': 3160, 'start_date': '2014-03-01'},
  {'count': 1430, 'start_date': '2014-04-01'},
  {'count': 866, 'start_date': '2014-05-01'},
  {'count': 616, 'start_date': '2014-06-01'},
  {'count': 988, 'start_date': '2014-07-01'},
  {'count': 2339, 'start_date': '2014-08-01'},
  {'count': 59, 'start_date': '2014-09-01'},
  {'count': 12, 'start_date': '2014-10-01'},
  {'count': 9, 'start_date': '2014-11-01'},
  {'count': 15, 'start_date': '2014-12-01'},
  {'count': 230, 'start_date': '2015-03-01'},
  {'count': 1128, 'start_date': '2015-04-01'},
  {'count': 624, 'start_date': '2015-05-01'},
  {'count': 924, 'start_date': '2015-06-01'},
  {'count': 1294, 'start_date': '2015-07-01'},
  {'count': 786, 'start_date': '2015-08-01'},
  {'count': 970, 'start_date': '2015-09-01'},
  {'count': 842, 'start_date': '2015-10-01'},
  {'count': 568, 'start_date': '2015-11-01'},
  {'count': 942, 'start_date': '2015-12-01'},
  {'count': 1797, 'start_date': '2016-01-01'},
  {'count': 982, 'start_date': '2016-02-01'},
  {'count': 951, 'start_date': '2016-03-01'},
  {'count': 75, 'start_date': '2016-04-01'},
  {'count': 817, 'start_date': '2016-05-01'},
  {'count': 816, 'start_date': '2016-06-01'},
  {'count': 338, 'start_date': '2016-07-01'},
  {'count': 81, 'start_date': '2016-08-01'},
  {'count': 438, 'start_date': '2016-09-01'},
  {'count': 466, 'start_date': '2016-10-01'},
  {'count': 419, 'start_date': '2016-11-01'},
  {'count': 620, 'start_date': '2016-12-01'},
  {'count': 580, 'start_date': '2017-01-01'},
  {'count': 89, 'start_date': '2017-02-01'},
  {'count': 58, 'start_date': '2017-03-01'},
  {'count': 140, 'start_date': '2017-04-01'},
  {'count': 267, 'start_date': '2017-05-01'},
  {'count': 822, 'start_date': '2017-06-01'},
  {'count': 602, 'start_date': '2017-07-01'},
  {'count': 8, 'start_date': '2017-08-01'},
  {'count': 34, 'start_date': '2017-09-01'},
  {'count': 22, 'start_date': '2017-10-01'},
  {'count': 35, 'start_date': '2017-11-01'},
  {'count': 38, 'start_date': '2017-12-01'},
  {'count': 170, 'start_date': '2018-01-01'},
  {'count': 100, 'start_date': '2018-02-01'},
  {'count': 17, 'start_date': '2018-03-01'},
  {'count': 2, 'start_date': '2018-04-01'},
  {'count': 19, 'start_date': '2018-05-01'}],
 'play_count': 34049,
 'play_time': 463.5547222222222,
 'playstyle': ['keyboard', 'tablet'],
 'post_count': 102,
 'pp': 5447,
 'previous_usernames': ['xIShockZ', 'Sugoi-_-Desu'],
 'ranked_and_approved_beatmapset_count': 0,
 'ranked_score': 10095687629,
 'replays_watched_by_others': 4,
 'replays_watched_counts': [{'count': 1, 'start_date': '2015-12-01'},
  {'count': 1, 'start_date': '2016-01-01'},
  {'count': 1, 'start_date': '2016-02-01'},
  {'count': 1, 'start_date': '2016-07-01'}],
 'total_hits': 8339466,
 'total_score': 36061405107,
 'username': 'Khan119'}

In [276]:
df = pd.DataFrame(list(data))
df_test = pd.DataFrame(list(data_test))
df = df.drop(['username', 'country', 'monthly_playcounts', 'previous_usernames', 'replays_watched_counts', "join_date"  ], axis=1)
df.head()

,A,S,SS,age,country_rank,favourite_beatmapset_count,follower_count,hit_accuracy,is_active,is_supporter,...,play_count,play_time,playstyle,post_count,pp,ranked_and_approved_beatmapset_count,ranked_score,replays_watched_by_others,total_hits,total_score
0,651.0,803.0,28.0,16.0,1.0,60,9204,98.3008,True,True,...,127203,1695.623333,"[keyboard, tablet]",9,14296,0,35956687428,188557,28378396,367849125665
1,1034.0,405.0,189.0,19.0,1.0,14,48041,98.9178,True,True,...,237913,2667.041111,"[keyboard, tablet]",15,14262,0,46649498415,1720746,42410479,467840602465
2,839.0,787.0,52.0,14.0,1.0,10,17495,98.4025,True,True,...,121355,1447.337500,[touch],10,13874,0,29827153244,464031,22063826,216798962074
3,1171.0,490.0,27.0,NaN,1.0,61,5413,99.0310,True,True,...,71481,931.634722,"[mouse, keyboard]",17,13590,0,15928388241,93667,15468426,108398366502
4,912.0,3450.0,234.0,22.0,1.0,51,5702,97.5871,True,True,...,122956,1748.853889,"[keyboard, tablet]",94,13371,0,53430781951,42061,30409606,327137749103

In [277]:
df_test = df_test.drop(['country', 'monthly_playcounts', 'previous_usernames', 'replays_watched_counts', "join_date"  ], axis=1)
df_test.head()

,A,S,SS,age,country_rank,favourite_beatmapset_count,follower_count,hit_accuracy,is_active,is_supporter,...,play_count,play_time,playstyle,post_count,ranked_and_approved_beatmapset_count,ranked_score,replays_watched_by_others,total_hits,total_score,username
0,480.0,641.0,86.0,NaN,1.0,11,95465,98.7997,True,True,...,21774,486.276944,None,202,0,32235365138,4908965,9091970,188171617520,Cookiezi
1,668.0,1644.0,224.0,18.0,1.0,35,11903,98.9098,True,True,...,134885,1820.493333,"[keyboard, tablet]",145,0,39052396402,379254,30252550,342047787910,filsdelama
2,781.0,1490.0,176.0,19.0,2.0,0,28943,98.5848,True,True,...,136758,1687.790000,"[keyboard, tablet]",3,0,42056979790,771609,33940529,403616203399,firebat92
3,502.0,564.0,18.0,17.0,2.0,0,5466,99.1761,True,True,...,47316,900.904722,"[keyboard, touch]",78,1,34128114878,126529,20722234,360959420559,idke
4,799.0,635.0,47.0,17.0,1.0,13,3857,98.6916,True,True,...,94729,1111.050278,"[keyboard, tablet]",25,0,23860960019,15461,16614535,172232720349,Abyssal

In [278]:
missing_data = df.isnull()
missing_data_test = df_test.isnull()

#missing_data.head(5)

In [279]:
df.dtypes

A                                       float64
S                                       float64
SS                                      float64
age                                     float64
country_rank                            float64
favourite_beatmapset_count                int64
follower_count                            int64
hit_accuracy                            float64
is_active                                  bool
is_supporter                               bool
level                                     int64
maximum_combo                             int64
play_count                                int64
play_time                               float64
playstyle                                object
post_count                                int64
pp                                        int64
ranked_and_approved_beatmapset_count      int64
ranked_score                              int64
replays_watched_by_others                 int64
total_hits                                int64
total_score                               int64
dtype: object

In [280]:
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")

A
False    6976
Name: A, dtype: int64

S
False    6976
Name: S, dtype: int64

SS
False    6976
Name: SS, dtype: int64

age
False    4878
True     2098
Name: age, dtype: int64

country_rank
False    6945
True       31
Name: country_rank, dtype: int64

favourite_beatmapset_count
False    6976
Name: favourite_beatmapset_count, dtype: int64

follower_count
False    6976
Name: follower_count, dtype: int64

hit_accuracy
False    6976
Name: hit_accuracy, dtype: int64

is_active
False    6976
Name: is_active, dtype: int64

is_supporter
False    6976
Name: is_supporter, dtype: int64

level
False    6976
Name: level, dtype: int64

maximum_combo
False    6976
Name: maximum_combo, dtype: int64

play_count
False    6976
Name: play_count, dtype: int64

play_time
False    6976
Name: play_time, dtype: int64

playstyle
False    6631
True      345
Name: playstyle, dtype: int64

post_count
False    6976
Name: post_count, dtype: int64

pp
False    6976
Name: pp, dtype: int64

ranked_and_approved_beatmapset_count
False    6976
Name: ranked_and_approved_beatmapset_count, dtype: int64

ranked_score
False    6976
Name: ranked_score, dtype: int64

replays_watched_by_others
False    6976
Name: replays_watched_by_others, dtype: int64

total_hits
False    6976
Name: total_hits, dtype: int64

total_score
False    6976
Name: total_score, dtype: int64

In [281]:
for column in missing_data_test.columns.values.tolist():
    print(column)
    print (missing_data_test[column].value_counts())
    print("")

A
False    2994
Name: A, dtype: int64

S
False    2994
Name: S, dtype: int64

SS
False    2994
Name: SS, dtype: int64

age
False    2087
True      907
Name: age, dtype: int64

country_rank
False    2975
True       19
Name: country_rank, dtype: int64

favourite_beatmapset_count
False    2994
Name: favourite_beatmapset_count, dtype: int64

follower_count
False    2994
Name: follower_count, dtype: int64

hit_accuracy
False    2994
Name: hit_accuracy, dtype: int64

is_active
False    2994
Name: is_active, dtype: int64

is_supporter
False    2994
Name: is_supporter, dtype: int64

level
False    2994
Name: level, dtype: int64

maximum_combo
False    2994
Name: maximum_combo, dtype: int64

play_count
False    2994
Name: play_count, dtype: int64

play_time
False    2994
Name: play_time, dtype: int64

playstyle
False    2840
True      154
Name: playstyle, dtype: int64

post_count
False    2994
Name: post_count, dtype: int64

ranked_and_approved_beatmapset_count
False    2994
Name: ranked_and_approved_beatmapset_count, dtype: int64

ranked_score
False    2994
Name: ranked_score, dtype: int64

replays_watched_by_others
False    2994
Name: replays_watched_by_others, dtype: int64

total_hits
False    2994
Name: total_hits, dtype: int64

total_score
False    2994
Name: total_score, dtype: int64

username
False    2994
Name: username, dtype: int64

In [282]:
df["playstyle"].replace(np.nan, "ThirdWay", inplace = True)
avg_age=df['age'].mean(axis=0)
df['age'].replace(np.nan, avg_age, inplace= True)
avg_rank=df['country_rank'].mean(axis=0)
df['country_rank'].replace(np.nan, avg_rank, inplace= True)
df["is_active"] = df["is_active"].astype(int)
df["is_supporter"] = df["is_supporter"].astype(int)
df["playstyle"] = df.playstyle.apply(lambda x: "-".join(x))

# for test data

df_test["playstyle"].replace(np.nan, "ThirdWay", inplace = True)
df_test['age'].replace(np.nan, avg_age, inplace= True)
df_test['country_rank'].replace(np.nan, avg_rank, inplace= True)
df_test["is_active"] = df_test["is_active"].astype(int)
df_test["is_supporter"] = df_test["is_supporter"].astype(int)
df_test["playstyle"] = df_test.playstyle.apply(lambda x: "-".join(x))

In [283]:
df.head()

,A,S,SS,age,country_rank,favourite_beatmapset_count,follower_count,hit_accuracy,is_active,is_supporter,...,play_count,play_time,playstyle,post_count,pp,ranked_and_approved_beatmapset_count,ranked_score,replays_watched_by_others,total_hits,total_score
0,651.0,803.0,28.0,16.000000,1.0,60,9204,98.3008,1,1,...,127203,1695.623333,keyboard-tablet,9,14296,0,35956687428,188557,28378396,367849125665
1,1034.0,405.0,189.0,19.000000,1.0,14,48041,98.9178,1,1,...,237913,2667.041111,keyboard-tablet,15,14262,0,46649498415,1720746,42410479,467840602465
2,839.0,787.0,52.0,14.000000,1.0,10,17495,98.4025,1,1,...,121355,1447.337500,touch,10,13874,0,29827153244,464031,22063826,216798962074
3,1171.0,490.0,27.0,20.443214,1.0,61,5413,99.0310,1,1,...,71481,931.634722,mouse-keyboard,17,13590,0,15928388241,93667,15468426,108398366502
4,912.0,3450.0,234.0,22.000000,1.0,51,5702,97.5871,1,1,...,122956,1748.853889,keyboard-tablet,94,13371,0,53430781951,42061,30409606,327137749103

In [284]:
A_max = df['A'].max()
S_max = df['S'].max()
SS_max = df['SS'].max()
age_max = df['age'].max()
favourite_beatmapset_count_max = df['favourite_beatmapset_count'].max()
follower_count_max = df['follower_count'].max()
hit_accuracy_max = df['hit_accuracy'].max()
play_count_max = df['play_count'].max()
play_time_max = df['play_time'].max()
post_count_max = df['post_count'].max()
ranked_score_max = df['ranked_score'].max()
replays_watched_by_others_max = df['replays_watched_by_others'].max()
total_hits_max = df['total_hits'].max()
total_score_max = df['total_score'].max()

df['A'] = df['A']/A_max
df['S'] = df['S']/S_max
df['SS'] = df['SS']/SS_max
df['age'] = df['age']/age_max
df['favourite_beatmapset_count'] = df['favourite_beatmapset_count']/favourite_beatmapset_count_max
df['follower_count'] = df['follower_count']/follower_count_max
df['hit_accuracy'] = df['hit_accuracy']/hit_accuracy_max
df['play_count'] = df['play_count']/play_count_max
df['play_time'] = df['play_time']/play_time_max
df['post_count'] = df['post_count']/post_count_max
df['ranked_score'] = df['ranked_score']/ranked_score_max
df['replays_watched_by_others'] = df['replays_watched_by_others']/replays_watched_by_others_max
df['total_hits'] = df['total_hits']/total_hits_max
df['total_score'] = df['total_score']/total_score_max


#for test data
df_test['A'] = df_test['A']/A_max
df_test['S'] = df_test['S']/S_max
df_test['SS'] = df_test['SS']/SS_max
df_test['age'] = df_test['age']/age_max
df_test['favourite_beatmapset_count'] = df_test['favourite_beatmapset_count']/favourite_beatmapset_count_max
df_test['follower_count'] = df_test['follower_count']/follower_count_max
df_test['hit_accuracy'] = df_test['hit_accuracy']/hit_accuracy_max
df_test['play_count'] = df_test['play_count']/play_count_max
df_test['play_time'] = df_test['play_time']/play_time_max
df_test['post_count'] = df_test['post_count']/post_count_max
df_test['ranked_score'] = df_test['ranked_score']/ranked_score_max
df_test['replays_watched_by_others'] = df_test['replays_watched_by_others']/replays_watched_by_others_max
df_test['total_hits'] = df_test['total_hits']/total_hits_max
df_test['total_score'] = df_test['total_score']/total_score_max

df.head()

,A,S,SS,age,country_rank,favourite_beatmapset_count,follower_count,hit_accuracy,is_active,is_supporter,...,play_count,play_time,playstyle,post_count,pp,ranked_and_approved_beatmapset_count,ranked_score,replays_watched_by_others,total_hits,total_score
0,0.111339,0.051036,0.002091,0.155340,1.0,0.60,0.125494,0.983008,1,1,...,0.359360,0.328639,keyboard-tablet,0.000559,14296,0,0.133398,0.029131,0.511140,0.483877
1,0.176843,0.025740,0.014117,0.184466,1.0,0.14,0.655027,0.989178,1,1,...,0.672126,0.516915,keyboard-tablet,0.000932,14262,0,0.173068,0.265848,0.763880,0.615408
2,0.143492,0.050019,0.003884,0.135922,1.0,0.10,0.238540,0.984025,1,1,...,0.342839,0.280517,touch,0.000621,13874,0,0.110658,0.071691,0.397404,0.285182
3,0.200274,0.031143,0.002017,0.198478,1.0,0.61,0.073805,0.990310,1,1,...,0.201940,0.180566,mouse-keyboard,0.001056,13590,0,0.059094,0.014471,0.278611,0.142590
4,0.155977,0.219270,0.017478,0.213592,1.0,0.51,0.077745,0.975871,1,1,...,0.347362,0.338956,keyboard-tablet,0.005842,13371,0,0.198227,0.006498,0.547725,0.430324

In [285]:
dummy_variable = pd.get_dummies(df["playstyle"])
dummy_variable_test = pd.get_dummies(df_test["playstyle"])

dummy_variable.head()

,T-h-i-r-d-W-a-y,keyboard,keyboard-tablet,keyboard-tablet-touch,keyboard-touch,mouse,mouse-keyboard,mouse-keyboard-tablet,mouse-keyboard-tablet-touch,mouse-keyboard-touch,mouse-tablet,mouse-tablet-touch,mouse-touch,tablet,tablet-touch,touch
0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0

In [286]:
df = pd.concat([df, dummy_variable], axis=1)
df_test = pd.concat([df_test, dummy_variable_test], axis=1)

# drop original column "fuel-type" from "df"
df.drop("playstyle", axis = 1, inplace=True)
df_test.drop("playstyle", axis = 1, inplace=True)
df.head()

,A,S,SS,age,country_rank,favourite_beatmapset_count,follower_count,hit_accuracy,is_active,is_supporter,...,mouse-keyboard,mouse-keyboard-tablet,mouse-keyboard-tablet-touch,mouse-keyboard-touch,mouse-tablet,mouse-tablet-touch,mouse-touch,tablet,tablet-touch,touch
0,0.111339,0.051036,0.002091,0.155340,1.0,0.60,0.125494,0.983008,1,1,...,0,0,0,0,0,0,0,0,0,0
1,0.176843,0.025740,0.014117,0.184466,1.0,0.14,0.655027,0.989178,1,1,...,0,0,0,0,0,0,0,0,0,0
2,0.143492,0.050019,0.003884,0.135922,1.0,0.10,0.238540,0.984025,1,1,...,0,0,0,0,0,0,0,0,0,1
3,0.200274,0.031143,0.002017,0.198478,1.0,0.61,0.073805,0.990310,1,1,...,1,0,0,0,0,0,0,0,0,0
4,0.155977,0.219270,0.017478,0.213592,1.0,0.51,0.077745,0.975871,1,1,...,0,0,0,0,0,0,0,0,0,0

In [287]:
y = np.array(df.pp)
usernames = np.array(df_test.username)
df.drop(['pp'], axis=1, inplace=True)
df_test.drop(['username'], axis=1, inplace=True)
X = np.array(df)
X_t = np.array(df_test)

In [288]:
print(y.shape)
print(X.shape)
print(X_t.shape)

(6976,)
(6976, 36)
(2994, 36)

In [229]:
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
# from sklearn.linear_model import LinearRegression
# from sklearn.metrics import mean_squared_error, r2_score
# reg = LinearRegression()
# reg = reg.fit(X_train, y_train)
# predict = reg.predict(X_test)
# # The coefficients
# print('Coefficients: \n', reg.coef_)
# # The mean squared error
# print("Mean squared error: %.2f" % mean_squared_error(y_test, predict)**0.5)
# # Explained variance score: 1 is perfect prediction
# print('Variance score: %.2f' % r2_score(y_test, predict))

# Model creation

In [322]:
from sklearn.preprocessing import PolynomialFeatures
from numpy.linalg import inv


def fit_linear_regression(X, Y, Lambda=0, degree=1):
    poly = PolynomialFeatures(degree)
    X = poly.fit_transform(X)
    # Identity matrix (number of parameters is the dimension)
    Identity = np.identity(len(X[1,:]))   
    # We don't add penalty to intercept
    Identity[0,0] = 0
    
    return inv(X.transpose().dot(X) + Lambda*Identity).dot(X.transpose()).dot(Y), X

def mean_square_loss(X, Y, b):

    return np.mean((X.dot(b) - Y) ** 2) ** (0.5)

In [323]:
beta, X_res = fit_linear_regression(X, y, 0, 1)
print(X_res.shape)
print(beta.shape)
# print(mean_square_loss(X_test, y_test, beta))

LinAlgError: Singular matrix

In [233]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=2)
kf.get_n_splits(X)

for train_index, test_index in kf.split(X):
   print("TRAIN:", train_index, "TEST:", test_index)
   X_train, X_test = X[train_index], X[test_index]
   y_train, y_test = y[train_index], y[test_index]

TRAIN: [3488 3489 3490 ... 6973 6974 6975] TEST: [   0    1    2 ... 3485 3486 3487]
TRAIN: [   0    1    2 ... 3485 3486 3487] TEST: [3488 3489 3490 ... 6973 6974 6975]

In [234]:
import matplotlib.pyplot as plt
means_train = []
means_test = []
for l in np.arange(0, 10, 1):
    beta = regression_model(y_train, X_train, l)
    mean_train = mean_square_loss(X_train, y_train, beta)
    mean_test = mean_square_loss(X_test, y_test, beta)
    means_test.append(mean_test)
    means_train.append(mean_train)
plt.clf()
plt.figure(figsize=(16,9))
plt.plot(np.arange(0, 10, 1), means_train, color="black", label="Loss train")
plt.plot(np.arange(0, 10, 1), means_test, color="red", label="Loss test")
plt.show()

LinAlgError: Singular matrix